baseURL = 'https://felixorbit.github.io/'
languageCode = 'zh-cn'
title = '理想假设'
theme = "hugo-digital-garden-theme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  name = "felixorbit"
  description = "宇宙大开发计划"
  initials = "felixorbit"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "#"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"

[menu]
  [[menu.main]]
    name = "博客"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "项目"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "阅读"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'